name: image_picker_saver
description:
  Image Picker and Saver plugin for Flutter
  Android supported
  IOS supported 8.0+
  fork form official plugin image_picker' 0.4.6
  and add saver to save image to gallery

authors:
  - Aaron Ho <cnhefang@gmail.com>

homepage: https://github.com/cnhefang/image_picker_saver
version: 0.3.0

flutter:
  plugin:
    androidPackage: io.flutter.plugins.imagepickersaver
    iosPrefix: FLT
    pluginClass: ImagePickerSaverPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
